version: '3'

services:
  db:
    image: postgres:11.5
    ports:
        - '5432:5432'
    volumes:
        - postgresql-data:/var/lib/postgresql/data
  api:
    build: ./
    image: enpit2019_er_leadleast_api
    ports:
      - '5000:5000'
    command: bash -c 'rm -f tmp/pids/server.pid && bundle exec rails s -p 5000 -b "0.0.0.0"'
    volumes:
      - ./:/app
    depends_on:
      - db

volumes:
  postgresql-data:

